# Generated by Django 4.2.27 on 2025-12-11 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conhecimento_das_leis_de_transito', models.BooleanField(default=False)),
                ('respeito_a_sinalizacao', models.BooleanField(default=False)),
                ('uso_correto_de_seta', models.BooleanField(default=False)),
                ('uso_correto_dos_retrovisores', models.BooleanField(default=False)),
                ('consciencia_de_ponto_cego', models.BooleanField(default=False)),
                ('percepcao_de_riscos', models.BooleanField(default=False)),
                ('leitura_de_placas', models.BooleanField(default=False)),
                ('conducao_defensiva', models.BooleanField(default=False)),
                ('controle_baixa_vel', models.BooleanField(default=False)),
                ('controle_alta_vel', models.BooleanField(default=False)),
                ('troca_marchas_suave', models.BooleanField(default=False)),
                ('uso_adequado_embreagem', models.BooleanField(default=False)),
                ('arranque_em_subida', models.BooleanField(default=False)),
                ('nao_deixar_morrer', models.BooleanField(default=False)),
                ('conducao_em_curvas', models.BooleanField(default=False)),
                ('manutencao_de_faixa', models.BooleanField(default=False)),
                ('baliza_com_caminhao', models.BooleanField(default=False)),
                ('estacionamento_em_doca', models.BooleanField(default=False)),
                ('re_em_linha_reta', models.BooleanField(default=False)),
                ('re_com_curva', models.BooleanField(default=False)),
                ('manobra_espaco_reduzido', models.BooleanField(default=False)),
                ('uso_correto_buzina', models.BooleanField(default=False)),
                ('uso_cinto_seguranca', models.BooleanField(default=False)),
                ('verificacao_previa_veiculo', models.BooleanField(default=False)),
                ('uso_de_epi', models.BooleanField(default=False)),
                ('respeito_limites_velocidade', models.BooleanField(default=False)),
                ('distancia_segura', models.BooleanField(default=False)),
                ('frenagem_segura', models.BooleanField(default=False)),
                ('reacao_emergencia', models.BooleanField(default=False)),
                ('pontualidade', models.BooleanField(default=False)),
                ('comunicacao_clara', models.BooleanField(default=False)),
                ('postura_profissional', models.BooleanField(default=False)),
                ('controle_emocional', models.BooleanField(default=False)),
                ('direcao_agressiva_nao_demonstrou', models.BooleanField(default=False)),
                ('respeito_pedestres', models.BooleanField(default=False)),
                ('respeito_demais_motoristas', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('observacoes_avaliador', models.TextField(blank=True)),
                ('pontos_fortes', models.TextField(blank=True)),
                ('pontos_a_melhorar', models.TextField(blank=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='clientes.client')),
            ],
        ),
    ]
